### ISSUE TITLE
Everyone launch JupyterHub individually

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/jupyterhub-tutorial#1]
Independent of training material, everyone should have a go at launching JupyterHub
- [x] @everett-toews 
- [x] @smashwilson 
- [x] @carolynvs 
- [x] @rgbkrk

**Comment by rgbkrk** [comment]
Tim's suped up version: https://github.com/betatim/carina-jupyterhub

**Comment by rgbkrk** [comment]
Docker spawner for JupyterHub: https://github.com/jupyter/dockerspawner

**Comment by rgbkrk** [comment]
OAuthenticator: https://github.com/jupyter/oauthenticator

**Comment by rgbkrk** [comment]
Actually, try this one out:

https://github.com/jupyter/dockerspawner/tree/master/examples/oauth

**Comment by carolynvs** [comment]
The PyLadies workshop the other week used Tim's. Individually it worked well but when 50 people tried to spawn at the same time, something about it broke. So we should try out hitting whatever we use to simulate workshop conditions.

**Comment by rgbkrk** [comment]
This Swarm spawner is what we'll want to adapt for ease of use on carina: https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py

**Comment by smashwilson** [comment]
Just as a head's up, I've noticed that `jupyter/jupyterhub:latest` is not up to date:

![screen shot 2016-02-04 at 8 00 07 am](https://cloud.githubusercontent.com/assets/17565/12815608/6aabaf2c-cb15-11e5-90ae-28a2b4bca547.jpeg)

Using `latest` I ran into problems with the GitHub OAuth authenticator nuking the `/hub/login/` route. Pinning my Dockerfile to `jupyter/jupyterhub:0.4.1` instead resolves the issue.

**Comment by smashwilson** [comment]
By the way, I'm working in [smashwilson/jupyterhub-carina](https://github.com/smashwilson/jupyterhub-carina) :wrench:

**Comment by smashwilson** [comment]
I'm up and running at [http://jupyterhub.azurefire.net/](http://jupyterhub.azurefire.net):

![screen shot 2016-02-04 at 10 28 56 am](https://cloud.githubusercontent.com/assets/17565/12819751/493523fe-cb2a-11e5-9c92-e21edd0210f1.jpeg)

![screen shot 2016-02-04 at 10 29 16 am](https://cloud.githubusercontent.com/assets/17565/12819752/4dcd9f4a-cb2a-11e5-84a9-74a80d3c164d.jpeg)

**Comment by carolynvs** [comment]
![betatim](https://cloud.githubusercontent.com/assets/1368985/12820283/054acaf0-cb24-11e5-900e-fa0db0ac264c.png)

**Comment by rgbkrk** [comment]
I'll go fix the Docker Hub builds for the official image.

**Comment by rgbkrk** [comment]
I triggered off the build for `latest`, though we'll definitely want to pin to `0.4.1`

**Comment by rgbkrk** [comment]
I'm up at http://jub.fict.io/

**Comment by etoews** [comment]
Giddy up http://jupyterhub.phymata.com/

<img width="716" alt="screen shot 2016-02-04 at 3 56 11 pm" src="https://cloud.githubusercontent.com/assets/634901/12831052/f5e21e40-cb57-11e5-9070-17ef9ff903e1.png">
