### ISSUE TITLE
JupyterHub on Carina section

### ISSUE THREAD

**Issue by etoews** [getcarina/jupyterhub-tutorial#10]
http://everett-toews.github.io/jupyterhub-on-docker-swarm/slides/#/jupyterhub-on-carina

All of the bit and pieces needed for this section.

**Comment by etoews** [comment]
What's a high-level outline for how this section would go?

@rgbkrk @carolynvs @smashwilson

**Comment by rgbkrk** [comment]
At this point, we can assume that the audience has successfully run containers on carina and understands a bit about swarm.

I'm assuming a bit of overlap with the plain jupyterhub section if we're talking about jupyterhub, though I think this may be fitting:
- launch a fresh cluster named `jupyterhub`
- make everyone clone this repo
- cd into the repo followed by jupyterhub-launch
- run `carina env jupyterhub`
- run `./launch.sh`
- help people get it running

**Comment by smashwilson** [comment]
I'd cover the mechanics of what JupyterHub needs to run:
- Building the Dockerfile, putting together the GitHub authenticator and Docker spawner.
- Mounting the Docker socket and certificates.
- TLS?
