### ISSUE TITLE
launch.py: add node constraint to jupyterhub-carina container build

### ISSUE THREAD

**Issue by smashwilson** [getcarina/jupyterhub-tutorial#22]
In `launch.py`, the `docker build` command needs to have a segment constraint to build in the right place:

``` bash
docker build --build-arg constraint:node==*n1 ...
```

**Comment by klvnnsrikanth** [comment]
@carolynvs Add to https://getcarina.com/docs/troubleshooting/run-container-using-custom-image/

**Comment by etoews** [comment]
@carolynvs @smashwilson @rgbkrk https://getcarina.com/docs/troubleshooting/run-container-using-custom-image/#use-a-constraint
