### ISSUE TITLE
Docker Swarm and Carina section

### ISSUE THREAD

**Issue by etoews** [getcarina/jupyterhub-tutorial#7]
http://everett-toews.github.io/jupyterhub-on-docker-swarm/slides/#/docker-swarm

All of the bit and pieces needed for this section.

**Comment by rgbkrk** [comment]
This combines some Swarm and Carina stuff: http://slides.com/kylekelley/swarm-workshop-4#/

**Comment by smashwilson** [comment]
Is there anything else we should cover in this section? I think we have this in place now.

**Comment by rgbkrk** [comment]
We can always open a new issue or PR if there are problems, this is in a pretty good state now.
